# Run me by typing `mythx analyze` in the directory of the yml file! :)

ci: true
confirm: true
analyze:
    mode: quick
    async: true
    create-group: true
    solc: 0.6.12
    remappings:
        - "@openzeppelin=node_modules/@openzeppelin"
    targets:
        - contracts/ReactMaker.sol:ReactMaker
        - contracts/amm/Pair.sol:UniswapV2Pair
        - contracts/amm/Factory.sol:UniswapV2Factory
        - contracts/amm/LP.sol:UniswapV2ERC20
        - contracts/amm/Router.sol:UniswapV2Router02
        - contracts/ReactRoll.sol:ReactRoll
        - contracts/ReactToken.sol:ReactToken
        - contracts/ReactBar.sol:ReactBar
        - contracts/ReactMaster.sol:ReactMaster
        - contracts/governance/Timelock.sol:Timelock
        - contracts/Migrator.sol:Migrator
